isims/config/routes.rb
Rails.application.routes.draw do
  resources :organizations do
    resources :entities do
      member do
        get 'validate_entity_info'
      end
    end
    member do
      get 'org_type'
      get 'is_validator'
      get  'is_producer'
    end
  end
  resources :entities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

isims/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

isims/app/models/entity.rb
class Entity < ApplicationRecord
end

isims/app/models/organization.rb
class Organization < ApplicationRecord
end

isims/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

isims/app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:name, :age, :dob, :education_specialization, :employer, :place_of_birth, :current_resident_country)
    end
end

isims/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy, :org_type, :is_validator, :is_producer]

  def org_type
    respond_to do |format|
      format.json { render json: @organization.org_type, status: :ok }
    end
  end

  def get_readable_fields
    respond_to do |format|
      format.json { render json: @organization.readable_ids }
    end
  end

  def get_writable_fields
    respond_to do |format|
      format.json { render json: @organization.writable_ids }
    end
  end

  def update_entity_info
    organization_id = params[:org_id]
    entity_id = params[:entity_id]
    key = params[:key]
    value = params[:value]
    org = Organization.find(organization_id.to_i)
    entity = Entity.find(entity_id.to_i)
    respond_to do |format|
      if org.writable_ids.split(",").include? key
        entity[key] = value
        entity.save!
        format.json { render json: true, status: :ok }
      else
        format.json { render json: false, status: :ok }
      end
    end
  end

  def validate_entity_info
    organization_id = params[:org_id]
    entity_id = params[:entity_id]
    key = params[:key]
    value = params[:value]
    org = Organization.find(organization_id.to_i)
    entity = Entity.find(entity_id.to_i)
    respond_to do |format|
      if org.readable_ids.split(",").include? key
        if "#{entity[key]}" == value
          format.json { render json: true, status: :ok }
        else
          format.json { render json: false, status: :ok }
        end
      else
        format.html { render :error }
      end
    end
  end

  def is_validator
    respond_to do |format|
      format.json { render json: @organization.is_validator, status: :ok }
    end
  end

  def is_producer
    respond_to do |format|
      p @organization
      format.json { render json: @organization.is_producer, status: :ok }
    end
  end
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :org_type, :readable_ids, :writable_ids, :is_producer, :is_validator)
    end
end

isims/app/helpers/application_helper.rb
module ApplicationHelper
end

isims/app/helpers/entities_helper.rb
module EntitiesHelper
end

isims/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

isims/app/views/entities/_form.html.erb
<%= form_with(model: entity, local: true) do |form| %>
  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.text_field :dob %>
  </div>

  <div class="field">
    <%= form.label :education_specialization %>
    <%= form.text_field :education_specialization %>
  </div>

  <div class="field">
    <%= form.label :employer %>
    <%= form.text_field :employer %>
  </div>

  <div class="field">
    <%= form.label :place_of_birth %>
    <%= form.text_field :place_of_birth %>
  </div>

  <div class="field">
    <%= form.label :current_resident_country %>
    <%= form.text_field :current_resident_country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

isims/app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

isims/app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Dob</th>
      <th>Education specialization</th>
      <th>Employer</th>
      <th>Place of birth</th>
      <th>Current resident country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.name %></td>
        <td><%= entity.age %></td>
        <td><%= entity.dob %></td>
        <td><%= entity.education_specialization %></td>
        <td><%= entity.employer %></td>
        <td><%= entity.place_of_birth %></td>
        <td><%= entity.current_resident_country %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

isims/app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Back', entities_path %>

isims/app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entity.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @entity.age %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @entity.dob %>
</p>

<p>
  <strong>Education specialization:</strong>
  <%= @entity.education_specialization %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @entity.employer %>
</p>

<p>
  <strong>Place of birth:</strong>
  <%= @entity.place_of_birth %>
</p>

<p>
  <strong>Current resident country:</strong>
  <%= @entity.current_resident_country %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>

isims/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Isims</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

isims/app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :org_type %>
    <%= form.text_field :org_type %>
  </div>

  <div class="field">
    <%= form.label :readable_ids %>
    <%= form.text_field :readable_ids %>
  </div>

  <div class="field">
    <%= form.label :writable_ids %>
    <%= form.text_field :writable_ids %>
  </div>

  <div class="field">
    <%= form.label :is_producer %>
    <%= form.check_box :is_producer %>
  </div>

  <div class="field">
    <%= form.label :is_validator %>
    <%= form.check_box :is_validator %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

isims/app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

isims/app/views/organizations/error.html.erb
<<h1>Error</h1>

isims/app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Readable ids</th>
      <th>Writable ids</th>
      <th>Is producer</th>
      <th>Is validator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.org_type %></td>
        <td><%= organization.readable_ids %></td>
        <td><%= organization.writable_ids %></td>
        <td><%= organization.is_producer %></td>
        <td><%= organization.is_validator %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

isims/app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

isims/app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @organization.org_type %>
</p>

<p>
  <strong>Readable ids:</strong>
  <%= @organization.readable_ids %>
</p>

<p>
  <strong>Writable ids:</strong>
  <%= @organization.writable_ids %>
</p>

<p>
  <strong>Is producer:</strong>
  <%= @organization.is_producer %>
</p>

<p>
  <strong>Is validator:</strong>
  <%= @organization.is_validator %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>